In [75]:
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

In [76]:
# from google.colab import drive
# drive.mount('/content/drive')

In [77]:
# df = pd.read_csv("/content/drive/MyDrive/DataSets/Flight Delay/DelayedFlights.csv")
df = pd.read_csv("../../../../DataSets/DelayedFlights.csv")
df.head()

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiIn,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,0,2008,1,3,4,2003.0,1955,2211.0,2225,WN,...,4.0,8.0,0,N,0,NaN,NaN,NaN,NaN,NaN
1,1,2008,1,3,4,754.0,735,1002.0,1000,WN,...,5.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN
2,2,2008,1,3,4,628.0,620,804.0,750,WN,...,3.0,17.0,0,N,0,NaN,NaN,NaN,NaN,NaN
3,4,2008,1,3,4,1829.0,1755,1959.0,1925,WN,...,3.0,10.0,0,N,0,2.0,0.0,0.0,0.0,32.0
4,5,2008,1,3,4,1940.0,1915,2121.0,2110,WN,...,4.0,10.0,0,N,0,NaN,NaN,NaN,NaN,NaN

In [78]:
df.isna().sum()

Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

In [79]:
df_clear = df.dropna(how='any',axis=0)
df_clear.isna().sum()

Unnamed: 0           0
Year                 0
Month                0
DayofMonth           0
DayOfWeek            0
DepTime              0
CRSDepTime           0
ArrTime              0
CRSArrTime           0
UniqueCarrier        0
FlightNum            0
TailNum              0
ActualElapsedTime    0
CRSElapsedTime       0
AirTime              0
ArrDelay             0
DepDelay             0
Origin               0
Dest                 0
Distance             0
TaxiIn               0
TaxiOut              0
Cancelled            0
CancellationCode     0
Diverted             0
CarrierDelay         0
WeatherDelay         0
NASDelay             0
SecurityDelay        0
LateAircraftDelay    0
dtype: int64

In [80]:
len(df_clear.index), len(df.index)

(1247486, 1936758)

In [81]:
columns_to_drop = ["Unnamed: 0","Cancelled","CancellationCode","Diverted","UniqueCarrier","TailNum"]
for value in columns_to_drop:
    if value in  df_clear.columns:
        df_clear.drop(columns_to_drop, axis=1, inplace= True);


df_clear= df_clear[df_clear['Origin']=='SEA']
df_clear.head()

C:\Users\sunil\AppData\Local\Temp/ipykernel_16728/2790678760.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clear.drop(columns_to_drop, axis=1, inplace= True);

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,...,Origin,Dest,Distance,TaxiIn,TaxiOut,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
1324,2008,1,3,4,1457.0,1405,1849.0,1750,972,172.0,...,SEA,ABQ,1180,6.0,15.0,24.0,0.0,7.0,0.0,28.0
1326,2008,1,3,4,1325.0,1255,1553.0,1510,318,88.0,...,SEA,BOI,399,2.0,25.0,11.0,0.0,13.0,0.0,19.0
1329,2008,1,3,4,2022.0,1925,2355.0,2300,1158,153.0,...,SEA,DEN,1024,7.0,18.0,0.0,0.0,0.0,0.0,55.0
1332,2008,1,3,4,2045.0,2010,2140.0,2105,775,55.0,...,SEA,GEG,224,5.0,15.0,0.0,0.0,4.0,0.0,31.0
1333,2008,1,3,4,1753.0,1640,1844.0,1735,1682,51.0,...,SEA,GEG,224,3.0,12.0,0.0,0.0,0.0,0.0,69.0

In [82]:
df_clear = pd.get_dummies(df_clear, columns=["Origin", "Dest"])
df_clear.drop(df_clear[""])
df_clear.head()

KeyError: ''

In [72]:
 df_clear.to_csv("../../../../Sample.csv")

In [65]:
X = df_clear.drop("ArrDelay", axis=1)
y = df_clear["ArrDelay"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

# Outlier Detection
We can use the dataset here, it has no outliers.

In [66]:
import numpy as np
from pprint import pprint

xbar = np.mean(y) 
s = np.std(y)
L=xbar-2*s
U=xbar+2*s
#print(L,U)
outliers = [] 
for i in y: 
    if i > U or i<L: 
        outliers.append(i) 
print('outliers in dataset is', outliers) 
print('Number of Outlier {} vs Number of Total Entries {}'.format(len(outliers),len(y)))

#This Can be the new Dataset Cleaned of Outliers.
clean_df=(df_clear[(df_clear.ArrDelay >= L) & (df_clear.ArrDelay <= U)])

outliers in dataset is [208.0, 193.0, 201.0, 232.0, 357.0, 189.0, 202.0, 256.0, 289.0, 329.0, 311.0, 245.0, 221.0, 206.0, 299.0, 176.0, 188.0, 235.0, 250.0, 251.0, 284.0, 235.0, 216.0, 200.0, 364.0, 215.0, 193.0, 243.0, 360.0, 181.0, 195.0, 187.0, 186.0, 191.0, 188.0, 257.0, 186.0, 232.0, 180.0, 189.0, 287.0, 180.0, 223.0, 175.0, 192.0, 194.0, 176.0, 238.0, 208.0, 202.0, 201.0, 206.0, 177.0, 256.0, 203.0, 184.0, 224.0, 197.0, 221.0, 248.0, 236.0, 301.0, 250.0, 231.0, 248.0, 188.0, 182.0, 202.0, 285.0, 192.0, 218.0, 180.0, 212.0, 187.0, 197.0, 192.0, 224.0, 184.0, 228.0, 282.0, 227.0, 228.0, 226.0, 206.0, 177.0, 195.0, 197.0, 339.0, 211.0, 326.0, 183.0, 279.0, 899.0, 411.0, 334.0, 380.0, 183.0, 194.0, 307.0, 302.0, 281.0, 189.0, 229.0, 244.0, 240.0, 186.0, 182.0, 184.0, 242.0, 408.0, 258.0, 235.0, 220.0, 204.0, 217.0, 445.0, 176.0, 186.0, 1267.0, 254.0, 292.0, 204.0, 274.0, 486.0, 1189.0, 191.0, 175.0, 862.0, 309.0, 196.0, 185.0, 225.0, 360.0, 342.0, 201.0, 181.0, 268.0, 177.0, 208.0, 188.0, 415.0, 224.0, 178.0, 178.0, 225.0, 251.0, 275.0, 223.0, 213.0, 239.0, 232.0, 201.0, 178.0, 218.0, 190.0, 403.0, 261.0, 178.0, 284.0, 247.0, 205.0, 191.0, 265.0, 341.0, 215.0, 215.0, 228.0, 189.0, 335.0, 194.0, 290.0, 194.0, 222.0, 186.0, 410.0, 560.0, 182.0, 212.0, 191.0, 178.0, 207.0, 193.0, 182.0, 334.0, 217.0, 221.0, 180.0, 182.0, 300.0, 192.0, 196.0, 235.0, 255.0, 178.0, 220.0, 195.0, 232.0, 187.0, 221.0, 340.0, 192.0, 256.0, 231.0, 298.0, 181.0, 311.0, 396.0, 232.0, 438.0, 185.0, 250.0, 185.0, 237.0, 259.0, 229.0, 190.0, 371.0, 214.0, 317.0, 179.0, 193.0, 180.0, 221.0, 204.0, 199.0, 240.0, 285.0, 203.0, 181.0, 185.0, 232.0, 197.0, 176.0, 400.0, 337.0, 212.0, 303.0, 281.0, 186.0, 235.0, 216.0, 345.0, 178.0, 197.0, 268.0, 207.0, 178.0, 189.0, 303.0, 180.0, 255.0, 198.0, 194.0, 265.0, 178.0, 228.0, 354.0, 422.0, 287.0, 177.0, 223.0, 191.0, 210.0, 175.0, 236.0, 262.0, 187.0, 249.0, 256.0, 228.0, 216.0, 195.0, 230.0, 206.0, 233.0, 201.0, 176.0, 204.0, 179.0, 188.0, 250.0, 255.0, 321.0, 289.0, 424.0, 177.0, 249.0, 434.0, 263.0, 185.0, 178.0, 254.0, 294.0, 187.0, 1510.0, 210.0, 192.0, 176.0, 227.0, 176.0, 175.0, 320.0, 414.0, 280.0, 193.0, 202.0, 275.0, 210.0, 178.0, 250.0, 213.0, 285.0, 211.0, 192.0, 192.0, 278.0, 221.0, 189.0, 224.0, 198.0, 327.0, 219.0, 199.0, 182.0, 192.0, 211.0, 213.0, 265.0, 253.0, 428.0, 325.0, 374.0, 337.0, 175.0, 592.0, 216.0, 178.0, 250.0, 396.0, 175.0, 396.0, 212.0, 260.0, 197.0, 213.0, 263.0, 191.0, 182.0, 260.0, 179.0, 180.0, 219.0, 355.0, 200.0, 227.0, 182.0, 175.0, 222.0, 245.0, 213.0, 842.0, 290.0, 284.0, 195.0, 256.0, 232.0, 358.0, 990.0, 222.0, 224.0, 186.0, 250.0, 187.0, 176.0, 289.0, 310.0, 1050.0, 194.0, 300.0, 570.0, 178.0, 185.0, 417.0, 270.0, 448.0, 175.0, 199.0, 258.0, 178.0, 330.0, 230.0, 190.0, 225.0, 197.0, 183.0, 426.0, 411.0, 889.0, 266.0, 176.0, 392.0, 180.0, 363.0, 209.0, 192.0, 243.0, 211.0, 277.0, 202.0, 243.0, 214.0, 184.0, 180.0, 217.0, 251.0, 209.0, 243.0, 296.0, 1097.0, 219.0, 476.0, 294.0, 724.0, 232.0, 192.0, 217.0, 214.0, 182.0, 221.0, 177.0, 178.0, 203.0, 183.0, 215.0, 346.0, 183.0, 478.0, 241.0, 249.0, 175.0, 195.0, 356.0, 315.0, 223.0, 267.0, 198.0, 234.0, 175.0, 179.0, 283.0, 180.0, 476.0, 268.0, 218.0, 220.0, 265.0, 212.0, 204.0, 220.0, 332.0, 187.0, 234.0, 177.0, 329.0, 300.0, 188.0, 250.0, 190.0, 428.0, 199.0, 236.0, 611.0, 240.0, 188.0, 297.0, 220.0, 176.0, 350.0, 191.0, 300.0, 176.0, 199.0, 380.0, 395.0, 246.0, 207.0, 217.0, 193.0, 456.0, 353.0, 230.0, 234.0, 353.0, 285.0, 199.0, 252.0, 262.0, 266.0, 238.0, 255.0, 204.0, 216.0, 451.0, 179.0, 198.0, 213.0, 382.0, 360.0, 731.0, 487.0, 209.0, 762.0, 307.0, 198.0, 801.0, 175.0, 238.0, 894.0, 438.0, 260.0, 191.0, 749.0, 283.0, 274.0, 260.0, 188.0, 1098.0, 341.0, 1112.0, 179.0, 375.0, 180.0, 500.0, 214.0, 212.0, 207.0, 227.0, 244.0, 201.0, 181.0, 258.0, 269.0, 186.0, 179.0, 218.0, 198.0, 213.0, 216.0, 178.0, 178.0, 188.0, 180.0, 190.0, 185.0, 196.0, 216.0, 186.0, 454.0, 801.0, 214.0, 279.0, 282.0, 351.0, 506.0, 372.0, 440.0, 279.0, 293.0, 368.0, 343.0, 303.0, 240.0, 346.0, 274.0, 376.0, 210.0, 200.0, 199.0, 179.0, 300.0, 204.0, 242.0, 247.0, 221.0, 179.0, 199.0, 198.0, 210.0, 195.0, 177.0, 282.0, 179.0, 201.0, 244.0, 186.0, 349.0, 181.0, 194.0, 240.0, 249.0, 257.0, 301.0, 214.0, 254.0, 223.0, 234.0, 268.0, 201.0, 268.0, 372.0, 245.0, 396.0, 177.0, 191.0, 262.0, 191.0, 217.0, 228.0, 360.0, 292.0, 272.0, 182.0]
Number of Outlier 622 vs Number of Total Entries 69820

In [67]:
clean_df

In [68]:
models1 = {}
models1["DTR"] = DecisionTreeRegressor()
model_acc1 = {}
for key1 in models1:
        for i in range(1):
                model_r = models1[key1]
                dt1 = model_r.fit(X_train1,y_train1) # fit the model
                # Y_pred = dt.predict(X_test) # predict
                a1 = model_r.score(X_test1,y_test1) # compute accuracy
        model_acc1[key1] = a1
print(model_acc1)

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

# If We manipulate DelArr

15< DelArr < 190: Var = 1243.84465 Score = 0.969

15< DelArr < 90: Var = 366 Score=0.95

15< DelArr < 60: Var = 151 Score= 0.94

15< DelArr < 30: Var = 18 Score= 0.91

15 == DelArr: Var= 0 Score = 1

In [ ]:
dfa=dfa[dfa['ArrDelay']==15]
#dfa = dfa[dfa['ArrDelay']<30]
dfa

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,FlightNum,ActualElapsedTime,...,Origin,Dest,Distance,TaxiIn,TaxiOut,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
3128,2008,1,4,5,1217.0,1210,1430.0,1415,481,133.0,...,0.0,38.0,671,7.0,15.0,7.0,0.0,8.0,0.0,0.0
6482,2008,1,6,7,1802.0,1745,2145.0,2130,408,163.0,...,0.0,44.0,1107,3.0,16.0,0.0,0.0,11.0,0.0,4.0
8507,2008,1,8,2,2132.0,2100,2320.0,2305,1687,108.0,...,0.0,38.0,671,5.0,12.0,0.0,0.0,0.0,0.0,15.0
9188,2008,1,9,3,1128.0,1100,1300.0,1245,73,92.0,...,0.0,52.0,605,4.0,13.0,3.0,0.0,0.0,0.0,12.0
9998,2008,1,10,4,1910.0,1850,2110.0,2055,390,120.0,...,0.0,50.0,697,3.0,13.0,0.0,0.0,0.0,0.0,15.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1915628,2008,12,1,1,806.0,800,1055.0,1040,279,169.0,...,0.0,47.0,1050,4.0,27.0,6.0,0.0,9.0,0.0,0.0
1918690,2008,12,20,6,1113.0,1050,1339.0,1324,293,146.0,...,0.0,29.0,965,5.0,15.0,10.0,0.0,0.0,0.0,5.0
1920814,2008,12,27,6,1641.0,1620,1909.0,1854,295,148.0,...,0.0,29.0,965,6.0,23.0,0.0,0.0,0.0,0.0,15.0
1922688,2008,12,29,1,1848.0,1840,2135.0,2120,1739,227.0,...,0.0,1.0,1449,6.0,12.0,8.0,0.0,7.0,0.0,0.0
1924564,2008,12,24,3,1626.0,1600,14.0,2359,1880,288.0,...,0.0,16.0,2401,10.0,12.0,0.0,0.0,5.0,0.0,10.0

In [ ]:
X = dfa.drop("ArrDelay", axis=1)
y = dfa["ArrDelay"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

import numpy as np
from pprint import pprint

xbar = np.mean(y) 
s = np.std(y)
L=xbar-2*s
U=xbar+2*s
#print(L,U)
outliers = [] 
for i in y: 
    if i > U or i<L: 
        outliers.append(i) 
print('outliers in dataset is', outliers) 
print('Number of Outlier {} vs Number of Total Entries {}'.format(len(outliers),len(y)))
from statistics import median, mode, variance
Mode=mode(y)
med=median(y)
V=variance(y)
print([Mode, med, V])

models = {}
models["DTR"] = DecisionTreeRegressor()
model_acc = {}
for key in models:
        for i in range(1):
                model_r = models[key]
                dt = model_r.fit(X_train,y_train) # fit the model
                # Y_pred = dt.predict(X_test) # predict
                a = model_r.score(X_test,y_test) # compute accuracy
        model_acc[key] = a
print(model_acc)

outliers in dataset is []
Number of Outlier 0 vs Number of Total Entries 574
[15.0, 15.0, 0.0]
{'DTR': 1.0}

# Mode Median and Variance Calculation

In [ ]:
from statistics import median, mode, variance
Mode=mode(y)
med=median(y)
V=variance(y)
print([Mode, med, V])

[15.0, 37.0, 3506.3076579540893]

# Continuation of Code

In [ ]:
models = {}
models["DTR"] = DecisionTreeRegressor()
# models["RFR"] = RandomForestRegressor()
#models["SVR"] = SVR()

In [ ]:
models

{'DTR': DecisionTreeRegressor()}

In [ ]:
model_acc = {}
for key in models:
        for i in range(1):
                model_r = models[key]
                dt = model_r.fit(X_train,y_train) # fit the model
                # Y_pred = dt.predict(X_test) # predict
                a = model_r.score(X_test,y_test) # compute accuracy
        model_acc[key] = a
print(model_acc)

{'DTR': 0.995156633647016}